[build-system]
requires = ["hatchling", "pytest"]
build-backend = "hatchling.build"

[project]
name = "poscores"
version = "0.1"
requires-python = ">=3.11"

[tool.ruff]
ignore-init-module-imports = true
